#+TITLE: Bigger Leaner Stronger notes

This file will register my thoughts, opinions, reflexions and some quotes that someday will
be useful for me(maybe for other persons too)

* Hidden barriers

** Questions
*** What is a protein?
*** What is carbohydrate
*** What is a sugar?
*** What is body fat?
*** What is muscle?
*** What is metabolism?
*** What is insulin?
*** What is a hormone?

** Quotes

#+begin_quote
The beginning of wisdom is the definition of terms.
#+end_quote
- SOCRATES

#+begin_quote
Why are people so susceptible to inaccuracies, lies, and oddball theories like these?

While that question might sound like it has a deep, complex answer, the reality is a
lot of it can be chalked up to the simplest of things: *misunderstood words*.
#+end_quote
- MIKE MATTHEWS

#+begin_quote
That's why learning the precise meanings of key words is the first major hurdle you have
to clear when you're trying to learn something new if you're going to have any hope of
gaining a deep and practical understanding of it.
#+end_quote
- MIKE MATTHEWS

* What most men will never know about getting fit chapter

** Questions
*** What is physiology?
The scientific study of the normal functions of living organisms and their parts.

** Quotes
#+begin_quote
Being ignorant is not so much a shame as being unwilling to learn.
#+end_quote
- BENJAMIN FRANKLIN

** Notes
 * Don't underestimate the destructive power of misunderstanding the basics of something
   you're trying to learn and apply.

** Concepts
*** Energy
 * Is the power received from electricity, fuel, food, and other sources to do work
   or produce motion.
 * Is the physical or mental strength of a person that can be directed toward some activity.

*** Matter
 * Is a physical substance, as distinct from the mind and spirit.
 * In physics (the branch of science concerned with matter and energy), matter is that which
   occupies space and can be moved with force, especially as distinct from energy.

*** Chemistry
 * Is the branch of science concerned with the substances of which matter is composed of,
   the investigation of their properties and reactions, and the use of such reactions to
   form new substances.

*** Chemical
 * Chemical means having to do with chemistry, or the interactions of substances as
   studied in chemistry
 * A chemical is any substances as studied in chemistry.
   + When people refer to chemicals, they're usually talking about manmade substances,
     but the definition isn't limited to just this meaning.

*** Organism
 * An organism is a single living thing, such as a person, animal or plant.

*** Cell
 * A cell is the basic unit of all living organisms. Some living organism exist only
   as a single cell, and according to the most recent research(the recent here is at
   some point before 2018), your body is made of approximately 37.2 trillion cells.
 * Cells produce energy, exchange information, multiply, and eventually die when
   their time has come.

*** Tissue(Tecido)
 * Is a group of cells in animals and plants that forms a definite kind of structural
   material with a specific functions

*** Muscle
 * Is a tissue in the body, often attached to bones, that can tighten and relax to
   produce motion.

*** Skeletal Muscle
 * Is a tissue connected to the skeleton to form part of the system that moves the
   limbs(membros) and other parts of the body.

*** Muscle Fiber
 * Also called a muscle cell or /*myocyte*/, is a colletion of long, threadlike strands
   called /*myofibrils*/(miofibrilas) that contract, along with other structural elements
   that you find in other cells in the human body.

*** Fat
 * Is an oily(oleoso) or greasy(gorduroso) substance found in animal bodies, specially
   when deposited as a layer under the skin or around certain organs.
 * Is a substance of this type derived from animals and plants that is solid or liquid in
   form, and often used in cooking.

*** Organ
 * An organ is a group of tissues that work together to perform a specific functions in
   an organism, like the heart, skin and lungs.
 * Skeletal muscle is not an organ because it contains just one type of tissue.

*** Gram
 * Is a unit of weight in the metric system. One pound is about 454 grams(fucking americans...).

*** Kilogram
 * Is a unit of weight in the metric system equal to 1000 grams, or 2.2 pounds.

*** Celsius
 * Is a scale of temperature on which water freezes at 0 degrees and boils at 100 degrees
 * In the Fahrenheit scale used in the united states(...), water freezes at 32 degrees
   and boils at 212 degrees.

*** Calorie
 * Is the energy needed to raise the temperature of 1 kilogram of water by 1 degree Celsius.
 * This is also called kilocalorie or large calorie, and is used to represent the energy value
   of food.

*** Element
 * An element(also called a chemical element) is a susbstance that can't be broken down into
   smaller parts by a chemical reaction.
 * There are more than 100 elements, and they are the primary building blocks of matter.

*** Compound(Composto)
 * Is a substance made up of two or more different elements.

*** Molecule
 * Is the smallest part particle of any compound that still exists as that substance.
 * If you were to break a molecule down any further, it would separate into the
   elements that make it up(meaning it would no longer exist as that original substance).

*** Acid
 * An acid is a chemical substance that can react with and sometimes dissolve other materials.

*** Amino Acid
 * An amino acid is a naturally ocurring compound found in proteins.

*** Protein
 * Is a naturally occuring compound that's composed of one or more long chains of amino acids.
 * Proteins are an essential part of all organisms and are used to create body tissues such as
   muscle, hair and skin, as well as various chemicals vital of life.

*** Essential Amino ACid
 * Is an amino acid needed by the body to maintain growth and health that must be obtained
   from food.

*** Gas
 * Is a substance that is in an air-like form(not solid or liquid).

*** Carbon
 * Is a nonmetallic element found in all life and much of the matter on earth.

*** Oxygen
 * Is a colorless, odorless gas that is necessary for most living things to survive.

*** Hydrogen
 * Is a colorless, odorless, flammable gas that is the simplest and most abundant element
   in the universe.

*** Carbohydrate
 * Is a molecule composed of carbon, oxygen, and hydrogen that can be broken down in the
   body to release energy.

*** Digestion
 * Is the process of breaking down food so it can be used by the body.
   
*** Enzyme
 * Is a substance produced by organisms that causes specific chemical reactions.
   
*** Metabolism
 * Is the series of physical and chemical processes that occur in an organism in
   order to maintain life.
 * Involves the production of energy as well as the creation, maintenance, and destruction
   of cells and tissues.

*** Anabolism
 * Is a metabolic process in a organism by which energy is used to make more complex
   substances(such as tissue) from simpler ones(such as protein).
   + This is also known as constructive metabolism.
 
*** Catabolism
 * Is the metabolic process by which more complex substances(such as proteins) are broken
   down into simpler ones(such as amino acids), together with the release of energy.
   + This is also known as destructive metabolism.

*** Healthy
 * If a body is healthy, it has good strength and high energy levels and is free from pain,
   ilness, damage, and dysfunction.
 * If something is healthy, it's beneficial to one's physical, mental, or emotional state.

*** Nutrient
 * Is a susbtance an organism needs to live and grow.

*** Food
 * Is material taken into the body to provide it with nutrients it needs for energy and growth.

*** Nourish(Nutrir)
 * to nourish is to provide with the food or other susbtances needed for growth, health and
   good condition.

*** Nutrition
 * Is the process of getting nourishment(alimentando or nutrido), specially the process of getting
   food and nutrients using them to grow bigger, build and replace tissues, and stay healthy.

*** Macronutrients
 * Is any of the nutritional components of the diet required in relatively large amounts.
   + Specifically, these are protein, carbohydrate, fat, and minerals, such as calcium, zinc,
     iron, magnesium, and phosphorous.

*** Vitamin
 * Is a substance that an organism needs for cells to function, grow, and develop correctly.

*** Hormone
 * Is a chemical that's transported by the blood or other bodily(corporal/corporais) fluids
   to cell and organs, where it causes some action or has some specific effect.

*** Mineral
 * Is a carbonless substance thar forms naturally in the earth.
 * Humans need various minerals, such as sodium, potassium, calcium, and zinc, for many
   different physiological functions, including building bones, making hormones, and
   regulating the heartbeat(magnesium).

*** Diet
 * A diet is the food and drink that a person usually consumes.
 * A diet is a special course of controlled or restricted intake of food or drink
   for a particular purpose, such as weight loss, exercice support, or maintenance therapy( a
   treatment designed to help another primary treatment to succeed).

*** Sugar
 * Is a class of sweet-tasting carbohydrate that comes from various plants, fruits, grains,
   and other sources.

*** Glucose
 * Is a sugar that occurs widely in nature and is an important energy source in organisms.
   + Glucose is a component of many carbohydrates.

*** Milligram
 * Is a unit of weight in the metric system equal to one-thousandth of gram.

*** Milliliter(Mililitros)
 * Is a unit of capacity in the metric system equal to a one-thousandth of a liter, which
   is equal to about 4.2 cups in the United States(...) customary system.

*** Blood Sugar
 * Is glucose in your blood.
 * Blood sugar refers to the concentration of glucose in your blood, measured in milligrams
   of glucose per 100 milliliters of blood.

*** Sucrose(sacarose)
 * Is a sugar that occurs naturally in most plants and is obtained commercially especially
   from sugarcane or sugar beets.
   + Sucrose is commonly known as table sugar.

*** Fructose
 * Is a very sweet sugar found in many fruits and honey, as well as sucrose and high-fructose
   corn syrup, both of which are about 50 percent fructose and 50 percent glucose.
   + Fructose is converted into glucose by the liver(figado) and then released into the blood for use.

*** Galactose
 * Is a type of sugar found in dairy(leitaria/laticinios) products that is metabolized similarly
   to fructose

*** Lactose
 * Lactose is a type of sugar present in milk that contains glucose and galactose.

*** Glycogen
 * Is a form of carbohydrate found primarily in the liver and muscle tissue.
 * Glycogen is stored energy and can be readily converted to glucose to satisfy the body's
   energy needs.

*** Simple Carbohydrate
 * Is a form of carbohydrate that breaks down quickly into glucose in the body.
   + Fructose, lactose, and sucrose are simple carbohydrates.

*** Complex Carbohydrate
 * Is a form of carbohydrate consisting of a chain of simple carbohydrates linked together.
   Because of this structure, a complex carbohydrate takes longer to break down into
   glucose in the body.
   + The sugars found in whole grains, beans, and vegetables are complex carbohydrates.

*** Starch(Amido)
 * Is a complex carbohydrate found naturally in many fruits and vegetables and added to
   certain foods to thicken them.

*** Insulin
 * Is a hormone made in the pancreas and released into the blood when you eat food.
 * Insulin causes muscles, organs, and fat tissue to absorb and use or store the
   nutrients from food.

*** Index
 * An index is a system of listing information in an order that allows one to compare
   it easily to other information.

*** Glycemic Index
 * (GI) is a numeric system that ranks how quickly the body convert various foods into
   glucose. Foods are ranked on a scale of 0 to 100 depending on how they affect blood
   sugar levels once eaten.
 * A GI rating of 55 and under is considered low on the index,
   while a rating of 56 to 69 is medium, and a rating of 70 or above is high.
 * Simple Carbohydrates are converted into glucose quickly and thus have high GI ratings.
   For example, sucrose's rating is 65, white bread's is 71, white rice is 89, and white
   potato is 82.
 * Complex carbohydrates are converted into glucose more slowly and thus have lower GI
   ratings. For example, apples' rating is 39, black beans'is 30, peanuts' is 7, and whole
   -grain pasta's is 42.

*** Fiber
 * Is a mostly indigestible type of carbohydrates found in many type of food, including fruits,
   vegetables, legumes, and grains.

*** Fatty Acid
 * Is an acid found in the fats and oils of animals and plants.

*** Essential Fatty Acid
 * Is a fatty acid that's vital for proper bodily function and must be obtained from food.

*** Satured Fat
 * Is a type of fat that's solid at room temperature and in many animal and some plant sources,
   including meat, cream, cheese, butter, lard, coconut oil, cottonseed oil, and palm kernel oil.

*** Unsatured Fat
 * Is a type of fat that's liquid at room temperature and found in many plant and some animal
   sources, including avocado, nuts, vegetable oils, and fish.

*** Trans Fatty Acid
 * Is a type of unsatured fatty acid that's uncommon in nature and usually created artificially.
 * "Trans fats" are often found in highly processed foods like cereals, baked goods, fast food, ice
   cream, and frozen dinners. Anything that contains "partially hydrogenated oil" contains trans
   fatty acids.

*** Cholesterol
 * Is a soft, waxy(ceroso) substance found in most body tissues
 * Cholesterol is an important part of the structure of cells and is used to create different hormones.

   
