#+TITLE: Bigger Leaner Stronger notes

This file will register my thoughts, opinions, reflexions and some quotes that someday will
be useful for me(maybe for other persons too)

* Hidden barriers

** Questions
*** What is a protein?
*** What is carbohydrate
*** What is a sugar?
*** What is body fat?
*** What is muscle?
*** What is metabolism?
*** What is insulin?
*** What is a hormone?

** Quotes

#+begin_quote
The beginning of wisdom is the definition of terms.
#+end_quote
- SOCRATES

#+begin_quote
Why are people so susceptible to inaccuracies, lies, and oddball theories like these?

While that question might sound like it has a deep, complex answer, the reality is a
lot of it can be chalked up to the simplest of things: *misunderstood words*.
#+end_quote
- MIKE MATTHEWS

#+begin_quote
That's why learning the precise meanings of key words is the first major hurdle you have
to clear when you're trying to learn something new if you're going to have any hope of
gaining a deep and practical understanding of it.
#+end_quote
- MIKE MATTHEWS

* What most men will never know about getting fit chapter

** Questions
*** What is physiology?
The scientific study of the normal functions of living organisms and their parts.

** Quotes
#+begin_quote
Being ignorant is not so much a shame as being unwilling to learn.
#+end_quote
- BENJAMIN FRANKLIN

** Notes
 * Don't underestimate the destructive power of misunderstanding the basics of something
   you're trying to learn and apply.

** Concepts
*** Energy
 * Is the power received from electricity, fuel, food, and other sources to do work
   or produce motion.
 * Is the physical or mental strength of a person that can be directed toward some activity.

*** Matter
 * Is a physical substance, as distinct from the mind and spirit.
 * In physics (the branch of science concerned with matter and energy), matter is that which
   occupies space and can be moved with force, especially as distinct from energy.

*** Chemistry
 * Is the branch of science concerned with the substances of which matter is composed of,
   the investigation of their properties and reactions, and the use of such reactions to
   form new substances.

*** Chemical
 * Chemical means having to do with chemistry, or the interactions of substances as
   studied in chemistry
 * A chemical is any substances as studied in chemistry.
   + When people refer to chemicals, they're usually talking about manmade substances,
     but the definition isn't limited to just this meaning.

*** Organism
 * An organism is a single living thing, such as a person, animal or plant.

*** Cell
 * A cell is the basic unit of all living organisms. Some living organism exist only
   as a single cell, and according to the most recent research(the recent here is at
   some point before 2018), your body is made of approximately 37.2 trillion cells.
 * Cells produce energy, exchange information, multiply, and eventually die when
   their time has come.

*** Tissue(Tecido)
 * Is a group of cells in animals and plants that forms a definite kind of structural
   material with a specific functions

*** Muscle
 * Is a tissue in the body, often attached to bones, that can tighten and relax to
   produce motion.

*** Skeletal Muscle
 * Is a tissue connected to the skeleton to form part of the system that moves the
   limbs(membros) and other parts of the body.

*** Muscle Fiber
 * Also called a muscle cell or /*myocyte*/, is a colletion of long, threadlike strands
   called /*myofibrils*/(miofibrilas) that contract, along with other structural elements
   that you find in other cells in the human body.

*** Fat
 * Is an oily(oleoso) or greasy(gorduroso) substance found in animal bodies, specially
   when deposited as a layer under the skin or around certain organs.
 * Is a substance of this type derived from animals and plants that is solid or liquid in
   form, and often used in cooking.

*** Organ
 * An organ is a group of tissues that work together to perform a specific functions in
   an organism, like the heart, skin and lungs.
 * Skeletal muscle is not an organ because it contains just one type of tissue.

*** Gram
 * Is a unit of weight in the metric system. One pound is about 454 grams(fucking americans...).

*** Kilogram
 * Is a unit of weight in the metric system equal to 1000 grams, or 2.2 pounds.

*** Celsius
 * Is a scale of temperature on which water freezes at 0 degrees and boils at 100 degrees
 * In the Fahrenheit scale used in the united states(...), water freezes at 32 degrees
   and boils at 212 degrees.
