#+TITLE: Swimming Experience

* Reasons
I needed to find a cardio working out routine to replace the tread mill(it's boring for me),
the outdoor running(i hate it) and exercice bike(i kind like itbut still someway boring too).
I was afraid of doing something like soccer or basketball cause i want to avoid injuries at all costs.
So inspired by boiselvagem and Nada melhor | Jota campos(check both channels on youtube) i decided to
get back to practice swimming! And now not only i want to become leaner with this, but also more resistent
to cold and long period exercising.

* Benefits(so far)
 1) Increase my mobility and flexibility in general.
 2) Will naturally lead to a powerful physical resistance.
 3) Will increase my performance in leg day!


* First Day - Lost in time
It was hard and intimidating! I used to practice swimming pool for 10 years but stopped by the age of
13yo and since then(now i am 23yo) never had another experience related too. I forgot how to correctly swim crawl
and breathe properly so a i got a lot of water in my noose at ther first tries... Eventually at that same
day i managed to improve almost everything but still pretty bad.

** Final conclusions
 + I have got even more hyped!
 + I managed to diving for 25 meters long without breathing.

* Second Day - Lost in time
This time i get back to the sea and it was a experimental class with a professional swimming teacher that helps
me retrieve the basics of swimming again(but now in open waters) and despites that is easier to swim in the sea
due to the salt, the tides can be dangerous and we need to know how to deal with it. I learned the 3 by 1 breathe
technic that is core to swim in the ocean cause you don't have a lane to guide you(frontal breathe to know where
you are) and also need to breathe to the other side than the waves when it is necessary.

** Final conclusions
 * I've injured my shoulder due to my lack of technic :(
 * I'll give more attention to correctly stretching before an exercice
 * I'll make more strengtheners exercices in the gym for my shoulders

* Third Day - 22/06/2022
It was my father's birthday so i went to swimming in special circunstances: after a brutal leg day! But why? well
i dont like to miss a workout day even when i have a good reason(dinner with my parents to celebrate my father) so
i organized everything to training before the night arrives and that means start earlier at the job to finish early
and go as soon as possible to the gym! After i did destroy my legs i moved on to the beach to my first class in the
sea swimming. But remember that i've injured my shoulder so was basically another leg working out(yes kkkkk)
to strenghten my kick in the water.

** Final conclusions
 * Don't push hard in the leg day if you intend to do a cardio that uses your legs

* Fourth Day
