#+TITLE: Swimming Experience

* Reasons
I needed to find a cardio working out routine to replace the tread mill(it's boring for me),
the outdoor running(i hate it) and exercice bike(i kind like itbut still someway boring too).
I was afraid of doing something like soccer or basketball cause i want to avoid injuries at all costs.
So inspired by boiselvagem and Nada melhor | Jota campos(check both channels on youtube) i decided to
get back to practice swimming! And now not only i want to become leaner with this, but also more resistent
to cold and long period exercising.

* Benefits(so far)
 1) Increase my mobility and flexibility in general.
 2) Will naturally lead to a powerful physical resistance.
 3) Will increase my performance in leg day!


* First day
It was hard and intimidating! I used to practice swimming pool for 10 years but stopped by the age of
13yo and since then(now i am 23yo) never had another experience related too. I forgot how to correctly swim crawl
and breathe properly so a i got a lot of water in my noose at ther first tries... Eventually at that the same
day i manage to improve almost everything but still pretty bad.

** Final conclusions
 + I have got even more hyped!
 + I managed to diving for 25 meters long without breathing.
